version: "3.0"
services:
  dht_sensor_simulator:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    container_name: dht_sensor_simulator
    environment:
      MODULE_NAME: "dht-sensor-simulator"
      MODULE_TYPE: "Input"
      EGRESS_URLS: "https://testdockercompose.free.beeceptor.com"
    ports:
      - 80:80
